package causality

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

var activityPattern = regexp.MustCompile(`^activity\s+([A-Za-z][A-Za-z0-9_]*)\(([^)]*)\)\s*->\s*([A-Za-z][A-Za-z0-9_]*)\s*$`)

func ParseGooo(source []byte) ([]Activity, error) {
	var activities []Activity
	scanner := bufio.NewScanner(bytes.NewReader(source))
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "//") {
			continue
		}
		if !strings.HasPrefix(line, "activity ") {
			continue
		}
		matches := activityPattern.FindStringSubmatch(line)
		if matches == nil {
			return nil, fmt.Errorf("line %d: malformed activity declaration", lineNumber)
		}
		activities = append(activities, Activity{
			Name:       matches[1],
			InputType:  strings.TrimSpace(matches[2]),
			OutputType: matches[3],
			SourceLine: lineNumber,
		})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(activities) == 0 {
		return nil, errors.New("no activities found in .gooo source")
	}
	return activities, nil
}

func LoadContract(data []byte) (Contract, error) {
	var contract Contract
	if err := json.Unmarshal(data, &contract); err != nil {
		return Contract{}, fmt.Errorf("decode contract: %w", err)
	}
	if contract.Schema == "" || contract.ContractID != ContractID {
		return Contract{}, errors.New("contract identity mismatch")
	}
	if len(contract.Cells) != 12 {
		return Contract{}, fmt.Errorf("contract has %d cells, want 12", len(contract.Cells))
	}
	if len(contract.ArtifactFiles) != len(ArtifactFiles) {
		return Contract{}, errors.New("contract artifact count mismatch")
	}
	for i, name := range ArtifactFiles {
		if contract.ArtifactFiles[i] != name {
			return Contract{}, fmt.Errorf("artifact %d is %q, want %q", i+1, contract.ArtifactFiles[i], name)
		}
	}
	return contract, nil
}

func BuildIR(sourcePath string, sourceDigest string, activities []Activity, contract Contract) (SemanticIR, error) {
	if len(activities) != len(contract.Cells) {
		return SemanticIR{}, fmt.Errorf("activity count %d does not match cell count %d", len(activities), len(contract.Cells))
	}
	seen := make(map[string]bool, len(activities))
	ir := SemanticIR{
		Schema:       "gooo/ci-time-causality/ir/v1",
		SourcePath:   sourcePath,
		SourceDigest: sourceDigest,
	}
	for i, activity := range activities {
		cell := contract.Cells[i]
		if seen[activity.Name] {
			return SemanticIR{}, fmt.Errorf("duplicate activity %q", activity.Name)
		}
		seen[activity.Name] = true
		if activity.Name != cell.Activity {
			return SemanticIR{}, fmt.Errorf("cell %q expects activity %q, got %q", cell.ID, cell.Activity, activity.Name)
		}
		ir.Nodes = append(ir.Nodes, ActivityIR{
			Ordinal:    cell.Ordinal,
			CellID:     cell.ID,
			Activity:   activity.Name,
			SourceLine: activity.SourceLine,
			Artifact:   cell.Artifact,
			Evaluator:  cell.Evaluator,
		})
	}
	return ir, nil
}

func GenerateEvaluator(ir SemanticIR) ([]byte, error) {
	if len(ir.Nodes) != 12 {
		return nil, errors.New("generated evaluator requires exactly 12 IR nodes")
	}
	var b strings.Builder
	b.WriteString("// Code generated by gooo-ci-time-causality; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString("const ContractID = \"" + ContractID + "\"\n")
	b.WriteString("const IRSchema = \"" + ir.Schema + "\"\n")
	b.WriteString("const SourceDigest = \"" + ir.SourceDigest + "\"\n\n")
	b.WriteString("var ActivityIDs = []string{\n")
	for _, node := range ir.Nodes {
		b.WriteString("\t\"" + node.Activity + "\",\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("func ActivityCount() int { return len(ActivityIDs) }\n")
	return []byte(b.String()), nil
}
